create table if not exists public.occurrences (
  id bigint generated by default as identity primary key,
  csi text not null,
  municipio text not null check (
    municipio in ('Icó', 'Orós', 'Umari', 'Lavras da Mangabeira', 'Cedro', 'Várzea Alegre')
  ),
  tipo_rede text not null check (tipo_rede in ('BT', 'MT')),
  referencia_local text not null,
  equipe_necessaria integer not null check (equipe_necessaria >= 0),
  observacoes text,
  status text not null default 'Pendente' check (status in ('Pendente', 'Resolvida')),
  created_at timestamptz not null default now()
);

create index if not exists occurrences_municipio_idx on public.occurrences (municipio);
create index if not exists occurrences_status_idx on public.occurrences (status);
